//! Signal-processing tables (IMDCT window / trig / permutation).
//!
//! The bulk of the data is generated by `build.rs` from the C source to
//! avoid transcription mistakes.

#![allow(clippy::approx_constant, clippy::excessive_precision)]

include!(concat!(env!("OUT_DIR"), "/tables_sigproc_gen.rs"));

pub fn bwin(nlnn: usize) -> &'static [Scalar] {
    match nlnn {
        LDAC_1FSLNN => &SA_BWIN_1FS,
        LDAC_2FSLNN => &SA_BWIN_2FS,
        _ => unreachable!(),
    }
}
pub fn wcos(nlnn: usize) -> &'static [Scalar] {
    match nlnn {
        LDAC_1FSLNN => &SA_WCOS_1FS,
        LDAC_2FSLNN => &SA_WCOS_2FS,
        _ => unreachable!(),
    }
}
pub fn wsin(nlnn: usize) -> &'static [Scalar] {
    match nlnn {
        LDAC_1FSLNN => &SA_WSIN_1FS,
        LDAC_2FSLNN => &SA_WSIN_2FS,
        _ => unreachable!(),
    }
}
pub fn rev_perm(nlnn: usize) -> &'static [u16] {
    match nlnn {
        LDAC_1FSLNN => &SA_REV_PERM_1FS,
        LDAC_2FSLNN => &SA_REV_PERM_2FS,
        _ => unreachable!(),
    }
}
