//! Generates `tables_sigproc.rs` from the C source at build time.
//!
//! The IMDCT window / cos / sin / permutation tables are large numeric
//! literals; regenerating them from the vetted C source prevents
//! transcription errors in the Rust port.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let src_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let c_src = src_dir.join("../src/tables_sigproc_ldac.o.c");
    println!("cargo:rerun-if-changed={}", c_src.display());
    let text = fs::read_to_string(&c_src).expect("read tables_sigproc_ldac.o.c");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from tables_sigproc_ldac.o.c\n");
    out.push_str("use crate::consts::*;\n\n");

    // ------------------------------------------------------------------
    // Float tables
    // ------------------------------------------------------------------
    struct FTab {
        c: &'static str,
        r: &'static str,
        len: &'static str,
    }
    let ftabs = [
        FTab {
            c: "sa_wsin_1fs_ldac",
            r: "SA_WSIN_1FS",
            len: "LDAC_1FSLSU",
        },
        FTab {
            c: "sa_wsin_2fs_ldac",
            r: "SA_WSIN_2FS",
            len: "LDAC_2FSLSU",
        },
        FTab {
            c: "sa_bwin_1fs_ldac",
            r: "SA_BWIN_1FS",
            len: "LDAC_1FSLSU",
        },
        FTab {
            c: "sa_bwin_2fs_ldac",
            r: "SA_BWIN_2FS",
            len: "LDAC_2FSLSU",
        },
        FTab {
            c: "sa_wcos_1fs_ldac",
            r: "SA_WCOS_1FS",
            len: "LDAC_1FSLSU",
        },
        FTab {
            c: "sa_wcos_2fs_ldac",
            r: "SA_WCOS_2FS",
            len: "LDAC_2FSLSU",
        },
        FTab {
            c: "ga_rsf_ldac",
            r: "GA_RSF",
            len: "LDAC_NIDWL",
        },
        FTab {
            c: "ga_sf_ldac",
            r: "GA_SF",
            len: "LDAC_NIDSF",
        },
        FTab {
            c: "ga_iqf_ldac",
            r: "GA_IQF",
            len: "LDAC_NIDWL",
        },
    ];
    for t in &ftabs {
        let vals = extract_floats(&text, t.c);
        out.push_str(&format!("pub static {}: [Scalar; {}] = [\n", t.r, t.len));
        for v in &vals {
            out.push_str(&format!("    {:e},\n", v));
        }
        out.push_str("];\n\n");
    }

    // ------------------------------------------------------------------
    // Integer permutation tables
    // ------------------------------------------------------------------
    struct ITab {
        c: &'static str,
        r: &'static str,
        len: &'static str,
    }
    let itabs = [
        ITab {
            c: "sa_rev_perm_1fs_ldac",
            r: "SA_REV_PERM_1FS",
            len: "LDAC_1FSLSU",
        },
        ITab {
            c: "sa_rev_perm_2fs_ldac",
            r: "SA_REV_PERM_2FS",
            len: "LDAC_2FSLSU",
        },
    ];
    for t in &itabs {
        let vals = extract_ints(&text, t.c);
        out.push_str(&format!("pub static {}: [u16; {}] = [\n    ", t.r, t.len));
        for (i, v) in vals.iter().enumerate() {
            out.push_str(&format!("{},", v));
            if (i + 1) % 16 == 0 {
                out.push_str("\n    ");
            }
        }
        out.push_str("\n];\n\n");
    }

    fs::write(out_dir.join("tables_sigproc_gen.rs"), out).unwrap();
}

fn extract_body<'a>(text: &'a str, name: &str) -> &'a str {
    let start = text
        .find(name)
        .unwrap_or_else(|| panic!("table {name} not found"));
    let open = text[start..].find('{').unwrap() + start + 1;
    let close = text[open..].find('}').unwrap() + open;
    &text[open..close]
}

fn extract_floats(text: &str, name: &str) -> Vec<f64> {
    extract_body(text, name)
        .split(',')
        .filter_map(|t| t.trim().parse::<f64>().ok())
        .collect()
}

fn extract_ints(text: &str, name: &str) -> Vec<i64> {
    extract_body(text, name)
        .split(',')
        .filter_map(|t| t.trim().parse::<i64>().ok())
        .collect()
}
